settings:
  name: Cloud Data Sense
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Cloud Data Sense docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Data Sense
          url: /concept-cloud-compliance.html
        - title: Deploy Cloud Data Sense
          entries:
            - title: Deploy in the cloud
              url: /task-deploy-cloud-compliance.html
            - title: Deploy on-prem with internet access
              url: /task-deploy-compliance-onprem.html
            - title: Deploy on-prem without internet access
              url: /task-deploy-compliance-dark-site.html
        - title: Activate scanning on your data sources
          entries:
            - title: Cloud Volumes ONTAP and on-prem ONTAP
              url: /task-getting-started-compliance.html
            - title: Azure NetApp Files
              url: /task-scanning-anf.html
            - title: Amazon FSx for ONTAP
              url: /task-scanning-fsx.html
            - title: Amazon S3 buckets
              url: /task-scanning-s3.html
            - title: Database schemas
              url: /task-scanning-databases.html
            - title: OneDrive accounts
              url: /task-scanning-onedrive.html
            - title: SharePoint accounts
              url: /task-scanning-sharepoint.html
            - title: Google Drive accounts
              url: /task-scanning-google-drive.html
            - title: File shares
              url: /task-scanning-file-shares.html
            - title: Object storage
              url: /task-scanning-object-storage.html
        - title: Integrate Active Directory
          url: /task-add-active-directory-datasense.html
        - title: Set up licensing
          url: /task-licensing-datasense.html
        - title: FAQ
          url: /faq-cloud-compliance.html
    - title: Use Cloud Data Sense
      entries:
        - title: View governance details about your data
          url: /task-controlling-governance-data.html
        - title: View compliance details about your data
          url: /task-controlling-private-data.html
        - title: Organize your private data
          url: /task-org-private-data.html
        - title: Manage your private data
          url: /task-managing-highlights.html
        - title: Change the scanning settings
          url: task-managing-repo-scanning.html
        - title: Generate reports
          url: /task-generating-compliance-reports.html
        - title: Respond to a DSAR
          url: /task-responding-to-dsar.html
        - title: Categories of private data
          url: /reference-private-data-categories.html
    - title: Manage Cloud Data Sense
      entries:
        - title: Add custom personal data identifiers
          url: /task-managing-data-fusion.html
        - title: View the status of Data Sense actions
          url: /task-view-compliance-actions.html
        - title: Audit the history of Data Sense actions
          url: /task-audit-data-sense-actions.html
        - title: Reduce the Data Sense scan speed
          url: /task-reduce-scan-speed.html
        - title: Remove data sources from Data Sense
          url: /task-managing-compliance.html
        - title: Uninstall Data Sense
          url: /task-uninstall-data-sense.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about Cloud Data Sense
          url: concept-cloud-compliance.html
        - title: What’s New
          url: whats-new.html
        - title: Deploy Data Sense in the cloud
          url: task-deploy-cloud-compliance.html
        - title: Deploy Data Sense on-premises with internet
          url: task-deploy-compliance-onprem.html
        - title: Deploy Data Sense on-premises without internet
          url: task-deploy-compliance-dark-site.html
        - title: Integrate Active Directory
          url: task-add-active-directory-datasense.html
        - title: Set up licensing
          url: task-licensing-datasense.html
    - title: Scan your working environments
      links:
        - title: Cloud Volumes ONTAP volumes
          url: task-getting-started-compliance.html
        - title: On-premises ONTAP volumes
          url: task-getting-started-compliance.html
        - title: Azure NetApp Files volumes
          url: task-scanning-anf.html
        - title: Amazon FSx for ONTAP volumes
          url: task-scanning-fsx.html
        - title: Amazon S3 buckets
          url: task-scanning-s3.html
    - title: Scan other data sources
      links:
        - title: Generic S3 buckets
          url: task-scanning-object-storage.html
        - title: Non-NetApp file shares
          url: task-scanning-file-shares.html
        - title: Database schemas
          url: task-scanning-databases.html
        - title: OneDrive accounts
          url: task-scanning-onedrive.html
        - title: SharePoint accounts
          url: task-scanning-sharepoint.html
        - title: Google Drive accounts
          url: task-scanning-google-drive.html
    - title: View details about your data
      links:
        - title: View files that contain private information
          url: task-controlling-private-data.html
        - title: View files that are duplicated in your storage
          url: task-controlling-private-data.html#checking-for-duplicate-files-in-your-storage-systems
        - title: Filter your data to view specific files
          url: task-controlling-private-data.html#filtering-data-in-the-data-investigation-page
        - title: Create policies to view your top searches
          url: task-org-private-data.html#controlling-your-data-using-policies
        - title: Generate compliance reports
          url: task-generating-compliance-reports.html
    - title: Organize your private data
      links:
        - title: Apply tags and owners to files that need attention
          url: task-org-private-data.html#applying-tags-to-manage-your-scanned-files
        - title: Categorize your data using AIP labels
          url: task-org-private-data.html#categorizing-your-data-using-aip-labels
        - title: Add your own custom personal data identifiers
          url: task-managing-data-fusion.html
    - title: Manage your private data
      links:
        - title: Copy source files
          url: task-managing-highlights.html#copying-source-files
        - title: Move source files
          url: task-managing-highlights.html#moving-source-files-to-an-nfs-share
        - title: Delete source files
          url: task-managing-highlights.html#deleting-source-files
        - title: Create email alerts when non-compliant data is found
          url: task-org-private-data.html#sending-email-alerts-when-non-compliant-data-is-found
        - title: Respond to a Data Subject Access Request
          url: task-responding-to-dsar.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central use cases
          url: https://cloud.netapp.com/netapp-cloud-data-sense
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events

