settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP classification docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /reference-limitations.html
    - title: Get started
      entries:
        - title: Learn about BlueXP classification
          url: /concept-cloud-compliance.html
        - title: Deploy BlueXP classification
          entries:
            - title: Deploy in the cloud using BlueXP
              url: /task-deploy-cloud-compliance.html
            - title: Install on a Linux host with internet access
              url: /task-deploy-compliance-onprem.html
            - title: Install on-prem without internet access
              url: /task-deploy-compliance-dark-site.html
            - title: Check that your Linux host is ready to install BlueXP classification
              url: /task-test-linux-system.html
        - title: Activate scanning on your data sources
          entries:
            - title: Cloud Volumes ONTAP and on-prem ONTAP
              url: /task-getting-started-compliance.html
            - title: Azure NetApp Files
              url: /task-scanning-anf.html
            - title: Amazon FSx for ONTAP
              url: /task-scanning-fsx.html
            - title: Amazon S3 buckets
              url: /task-scanning-s3.html
            - title: Database schemas
              url: /task-scanning-databases.html
            - title: OneDrive accounts
              url: /task-scanning-onedrive.html
            - title: SharePoint accounts
              url: /task-scanning-sharepoint.html
            - title: Google Drive accounts
              url: /task-scanning-google-drive.html
            - title: File shares
              url: /task-scanning-file-shares.html
            - title: Object storage
              url: /task-scanning-object-storage.html
        - title: Integrate Active Directory
          url: /task-add-active-directory-datasense.html
        - title: Set up licensing
          url: /task-licensing-datasense.html
        - title: FAQ
          url: /faq-cloud-compliance.html
    - title: Use BlueXP classification
      entries:
        - title: View governance details about your data
          url: /task-controlling-governance-data.html
        - title: View compliance details about your data
          url: /task-controlling-private-data.html
        - title: Categories of private data
          url: /reference-private-data-categories.html
        - title: Investigate your data
          url: /task-investigate-data.html
        - title: Organize your private data
          url: /task-org-private-data.html
        - title: Assign policies to your data
          url: /task-using-policies.html 
        - title: Manage your private data
          url: /task-managing-highlights.html
        - title: Monitor and manage file access events
          url: /task-manage-file-access-events.html
        - title: Change scan settings
          url: task-managing-repo-scanning.html
        - title: Generate compliance reports
          url: /task-generating-compliance-reports.html
    - title: Manage BlueXP classification
      entries:
        - title: Add custom personal data identifiers
          url: /task-managing-data-fusion.html
        - title: View the status of BlueXP classification actions
          url: /task-view-compliance-actions.html
        - title: Define existing Group IDs as "open to organization"
          url: /task-add-group-id-as-open.html
        - title: Audit the history of BlueXP classification actions
          url: /task-audit-data-sense-actions.html
        - title: Reduce the BlueXP classification scan speed
          url: /task-reduce-scan-speed.html
        - title: Remove data sources from BlueXP classification
          url: /task-managing-compliance.html
        - title: Uninstall BlueXP classification
          url: /task-uninstall-data-sense.html
    - title: Reference
      entries:
        - title: Supported BlueXP classification instance types
          url: /reference-instance-types.html
        - title: Metadata collected from data sources
          url: /reference-collected-metadata.html
        - title: Log in to the BlueXP classification system
          url: /reference-log-in-to-instance.html
        - title: BlueXP classification APIs
          url: /api-classification.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
