settings:
  name: Cloud Data Sense
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Data Sense docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Data Sense
          url: /concept-cloud-compliance.html
        - title: Deploy Cloud Data Sense
          entries:
            - title: Deploy in the cloud
              url: /task-deploy-cloud-compliance.html
            - title: Deploy on-prem with internet access
              url: /task-deploy-compliance-onprem.html
            - title: Deploy on-prem without internet access
              url: /task-deploy-compliance-dark-site.html
        - title: Activate scanning on your data sources
          entries:
            - title: Cloud Volumes ONTAP and on-prem ONTAP
              url: /task-getting-started-compliance.html
            - title: Azure NetApp Files
              url: /task-scanning-anf.html
            - title: Amazon FSx for ONTAP
              url: /task-scanning-fsx.html
            - title: Amazon S3 buckets
              url: /task-scanning-s3.html
            - title: Database schemas
              url: /task-scanning-databases.html
            - title: OneDrive accounts
              url: /task-scanning-onedrive.html
            - title: SharePoint accounts
              url: /task-scanning-sharepoint.html
            - title: File shares
              url: /task-scanning-file-shares.html
            - title: Object storage
              url: /task-scanning-object-storage.html
        - title: Integrate Active Directory
          url: /task-add-active-directory-datasense.html
        - title: Set up licensing
          url: /task-licensing-datasense.html
        - title: FAQ
          url: /faq-cloud-compliance.html
    - title: Use Cloud Data Sense
      entries:
        - title: View governance details about your data
          url: /task-controlling-governance-data.html
        - title: View compliance details about your data
          url: /task-controlling-private-data.html
        - title: Organize your private data
          url: /task-org-private-data.html
        - title: Manage your private data
          url: /task-managing-highlights.html
        - title: Add custom personal data identifiers
          url: /task-managing-data-fusion.html
        - title: Generate reports
          url: /task-generating-compliance-reports.html
        - title: Respond to a DSAR
          url: /task-responding-to-dsar.html
        - title: Categories of private data
          url: /reference-private-data-categories.html
        - title: Remove data sources from Data Sense
          url: /task-managing-compliance.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: tile name
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
