---
sidebar: sidebar
permalink: reference-limitations.html
keywords: limitations, data sense, classification, bluexp, scan shares
summary: Known limitations identify functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.


== BlueXP classification release temporarily removed options

The December 2023 (version 1.26.6) release temporarily removed the following options: 

* The option to activate audit log collection has been disabled. 
* During the Directories investigation, the option to calculate the number of personal identifiable information  (PII) data by Directories is not available. 
* The option to integrate data using Azure Information Protection (AIP) labels has been disabled. 

== BlueXP classification scanning limitations


=== BlueXP classification scans only one share under a volume

If you have multiple file shares under a single volume, BlueXP classification scans the share with the highest hierarchy. For example, if you have shares like the following:

* /A
* /A/B
* /C
* /D/E

Then the data in /A will be scanned. The data in /C and /D will not be scanned.

.Workaround

There is a workaround to make sure you are scanning data from all the shares in your volume. Follow these steps:

. In the working environment, add the volume to be scanned.
. After BlueXP classification has completed scanning the volume, go to the _Data Investigation_ page and create a filter to see which share is being scanned:
+
You'll filter the data by "Working Environment Name" and "Directory Type = Share" to see which share is being scanned.
. Get the complete list of shares that exist in the volume so you can see which shares are not being scanned.
. link:task-scanning-file-shares.html[Add the remaining shares to a share group].
+
You'll need to add all the shares individually, for example:
+
 /C
 /D
 
. Perform these steps for each volume in the working environment that has multiple shares.
