---
sidebar: sidebar
permalink: task-manage-file-access-events.html
keywords: compliance, actions, view progress, audit, logs, installation
summary: DYou can configure Data Sense to log events to a file whenever one of the files you are scanning has been accessed or changed. Then you can view the contents of the File Access Audit Log, or download them, to see what file changes have occurred, and by whom. 
---

= Monitor and manage file access events
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can configure Data Sense to log events to a file whenever one of the files you are scanning has been accessed or changed. Then you can view the contents of the File Access Audit Logs, or download them, to see what file changes have occurred, and by whom. 

You can configure file access audit logging for any critical volumes in your working environments. You can configure Data Sense to capture the following actions and the users who performed the action: Read, Write, Delete, Rename, Change owner/permissions, and Change SACL/DACL. See XYZ for details.......

For example, you can see the name of the person who has made a change to a files, and when the change was made.

== Supported data sources

Data Sense can log file access events for the following data sources:

* On-premises ONTAP
* Cloud Volumes ONTAP
* Azure NetApp Files
* FSx for ONTAP

You must have Active Directory configured for these data sources so that Data Sense can capture the name of the person who accessed the files.

== Log file contents

Each line in the audit log contains information in this format:

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* Date and time - full timestamp for the event
* Status - INFO, WARNING
* Action type (delete, copy, move, create policy, update policy, rescan files, download JSON report, etc.)
* File name (if the action is relevant to a file)
* Details for the action - what was done: depends on the action

** Policy name
** For move - Source and destination
** For copy - Source and destination
** For tag - tag name
** For assign to - user name
** For email alert - email address / account

For example, the following lines from the log file show a successful copy operation and a failed copy operation.

 2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
 2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE

== Accessing the log file

The management audit log files are located on the Data Sense machine in: `/opt/netapp/audit_logs/`

The installation audit log files are written to `/ops/netapp/install_logs`

Each log file can be a maximum of 10 MB in size. When that limit is reached, a new log file is started. The log files are named "File_Access_Aidit_<volume-name>_<timestamp>.log", "DataSense_audit.log.1", "DataSense_audit.log.2", and so on. A maximum of 100 log files are retained on the system - old log files are deleted automatically after the maximum has been reached.

When Data Sense is installed on your premises, you can navigate directly to the log file.

When Data Sense is deployed in the cloud, you need to SSH to the Data Sense instance. You SSH to the system by entering the user and password, or by using the SSH key you provided during the BlueXP Connector installation. The SSH command is:

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>

* <path_to_the_ssh_key> = location of ssh authentication keys
* <machine_user>:

** For AWS: use the <ec2-user>
** For Azure: use the user created for the BlueXP instance
** For GCP: use the user created for the BlueXP instance

* <datasense_ip> = IP address of the virtual machine instance

Note that you'll need to modify the security group inbound rules to access the system in the cloud. For details, see: 

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-aws.html[Security group rules in AWS^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html[Security group rules in Azure^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-gcp.html[Firewall rules in Google Cloud^]

