---
sidebar: sidebar
permalink: task-deploy-overview.html
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification
summary: Plan which deployment of BlueXP classification meets your needs.
---

= Which BlueXP classification deployment should you use?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can deploy BlueXP classification in different ways. Learn which method meets your needs. 

BlueXP classification can be deployed in the following ways: 

* link:task-deploy-cloud-compliance.html[Deploy in the cloud using BlueXP]. BlueXP will deploy the BlueXP classification instance in the same cloud provider network as the BlueXP Connector.
* link:task-deploy-compliance-onprem.html[Install on a Linux host with internet access]. Install BlueXP classification on a Linux host in your network, or on a Linux host in the cloud, that has internet access. This type of installation may be a good option if you prefer to scan on-premises ONTAP systems using a BlueXP classification instance that's also located on premises—but this is not a requirement.
* link:task-deploy-compliance-dark-site.html[Install on a Linux host in an on-premises site without internet access], also known as _private mode._ This type of installation, which uses an installation script, is good for your secure sites. 

Both the installation on a Linux host with internet access and the on-premises installation on a Linux host without internet access use an installation script. The script starts by checking if the system and environment meet the prerequisites. If the prerequisites are met, the installation starts. If you would like to verify the prerequisites independently of running the BlueXP classification installation, there is a separate software package you can download that only tests for the prerequisites.

Refer to link:task-test-linux-system.html[Check that your Linux host is ready to install BlueXP classification].

