---
sidebar: sidebar
permalink: task-test-linux-system.html
keywords: cloud compliance, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, dark site
summary: Before installing BlueXP classification manually on a Linux host you can run a script on the host to verify that all the prerequisites are in place for installing BlueXP classification. You can run this script on a Linux host in your network, or on a Linux host in the cloud. The host can be connected to the internet, or the host can reside in a site that doesn't have internet access.
---

= Check that your Linux host is ready to install BlueXP classification
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before installing BlueXP classification manually on a Linux host, you can run a script on the host to verify that all the prerequisites are in place for installing BlueXP classification. You can run this script on a Linux host in your network, or on a Linux host in the cloud. The host can be connected to the internet, or the host can reside in a site that doesn't have internet access (a _dark site_).

There is also a prerequisite test script that is part of the BlueXP classification installation script. The script described here is specifically designed for users who want to verify the Linux host independently of running the BlueXP classification installation script.

== Getting Started

You'll perform the following tasks.

. Optionally, install a BlueXP Connector if you don't already have one installed. You can run the test script without having a Connector installed, but the script checks for connectivity between the Connector and the BlueXP classification host machine - so it is recommended that you have a Connector.
. Prepare the host machine and verify that it meets all the requirements.
. Enable outbound internet access from the BlueXP classification host machine.
. Verify that all required ports are enabled on all systems.
. Download and run the Prerequisite test script.

== Create a Connector

A BlueXP Connector is required before you can install and use BlueXP classification. You can, however, run the Prerequisites script without a Connector.

You can https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html[install the Connector on-premises^] on a Linux host in your network or on a Linux host in the cloud. Some users planning to install BlueXP classification on-prem may also choose to install the Connector on-prem.

To create a Connector in your cloud provider environment, see https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html[creating a Connector in AWS^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html[creating a Connector in Azure^], or https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html[creating a Connector in GCP^]. 

You'll need the IP address or host name of the Connector system when running the Prerequisites script. You'll have this information if you installed the Connector in your premises. If the Connector is deployed in the cloud, you can find this information from the BlueXP console: click the Help icon, select *Support*, and click *BlueXP Connector*.

== Verify host requirements

BlueXP classification software must run on a host that meets specific operating system requirements, RAM requirements, software requirements, and so on. 

include::_include/host-requirements.adoc[]

* *Firewalld considerations*: If you are planning to use `firewalld`, we recommend that you enable it before installing BlueXP classification. Run the following commands to configure `firewalld` so that it is compatible with BlueXP classification:
+
 firewall-cmd --permanent --add-service=http
 firewall-cmd --permanent --add-service=https
 firewall-cmd --permanent --add-port=80/tcp
 firewall-cmd --permanent --add-port=8080/tcp
 firewall-cmd --permanent --add-port=443/tcp
 firewall-cmd --reload
+
If you're planning to use additional BlueXP classification hosts as scanner nodes (in a distributed model), add these rules to your primary system at this time:
+
 firewall-cmd --permanent --add-port=2377/tcp
 firewall-cmd --permanent --add-port=7946/udp
 firewall-cmd --permanent --add-port=7946/tcp
 firewall-cmd --permanent --add-port=4789/udp
+
Note that you must restart Docker or Podman whenever you enable or update `firewalld` settings.
//add 'or Podman' in 2nd bullet

== Enable outbound internet access from BlueXP classification

BlueXP classification requires outbound internet access. If your virtual or physical network uses a proxy server for internet access, ensure that the BlueXP classification instance has outbound internet access to contact the following endpoints.

TIP: This section is not required for host systems installed in sites without internet connectivity. 

[cols="43,57",options="header"]
|===
| Endpoints
| Purpose

| \https://api.bluexp.netapp.com | Communication with the BlueXP service, which includes NetApp accounts.

|
\https://netapp-cloud-account.auth0.com
\https://auth0.com

| Communication with the BlueXP website for centralized user authentication.

|
\https://support.compliance.api.bluexp.netapp.com/
\https://hub.docker.com
\https://auth.docker.io
\https://registry-1.docker.io
\https://index.docker.io/
\https://dseasb33srnrn.cloudfront.net/
\https://production.cloudflare.docker.com/

| Provides access to software images, manifests, templates, and to send logs and metrics.

| \https://support.compliance.api.bluexp.netapp.com/ | Enables NetApp to stream data from audit records.

|
\https://github.com/docker
\https://download.docker.com

| Provides prerequisite packages for docker installation.

|
\http://mirror.centos.org
\http://mirrorlist.centos.org
\http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm

| Provides prerequisite packages for CentOS installation.

|
\http://packages.ubuntu.com/
\http://archive.ubuntu.com

| Provides prerequisite packages for Ubuntu installation.
|===

== Verify that all required ports are enabled

You must ensure that all required ports are open for communication between the Connector, BlueXP classification, Active Directory, and your data sources.

[cols="25,25,50",options="header"]
|===
| Connection Type
| Ports
| Description

|Connector <> BlueXP classification | 8080 (TCP), 443 (TCP), and 80 | The firewall or routing rules for the Connector must allow inbound and outbound traffic over port 443 to and from the BlueXP classification instance.

Make sure port 8080 is open so you can see the installation progress in BlueXP.
|Connector <> ONTAP cluster (NAS) | 443 (TCP)  a| BlueXP discovers ONTAP clusters using HTTPS. If you use custom firewall policies, the Connector host must allow outbound HTTPS access through port 443. If the Connector is in the cloud, all outbound communication is allowed by the predefined firewall or routing rules.

|===

== Run the BlueXP classification Prerequisites script

Follow these steps to run the BlueXP classification Prerequisites script.

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B[Watch this video^] to see how to run the Prerequisites script and interpret the results.

.What you'll need

* Verify that your Linux system meets the <<Verify host requirements,host requirements>>.
* Verify that the system has the two prerequisite software packages installed (Docker Engine or Podman, and Python 3).
//add 'or Podman'
* Make sure you have root privileges on the Linux system.
//* If you're using a proxy for access to the internet:
//** You'll need the proxy server information (IP address or host name, connection port, connection scheme: https or http, user name and password).
//** If the proxy is performing TLS interception, you'll need to know the path on the Linux system where the TLS CA certificates are stored.
//* Verify that your offline environment meets the required <<Enable outbound internet access from BlueXP classification,permissions and connectivity>>.

.Steps

. Download the BlueXP classification Prerequisites script from the https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/[NetApp Support Site^]. The file you should select is named *standalone-pre-requisite-tester-<version>*.

. Copy the file to the Linux host you plan to use (using `scp` or some other method).

. Assign permissions to run the script.
+
[source,cli]
chmod +x standalone-pre-requisite-tester-v1.25.0

. Run the script using the following command.
+
[source,cli]
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
+
Add the option "--darksite" only if you are running the script on a host that doesn't have internet access. Certain prerequisite tests are skipped when the host is not connected to the internet.

. The script prompts you for the IP address of the BlueXP classification host machine.
+
** Enter the IP address or host name.

. The script prompts whether you have an installed BlueXP Connector. 
+
** Enter *N* if you do not have an installed Connector.
** Enter *Y* if you do have an installed Connector. And then enter the IP address or host name of the BlueXP Connector so the test script can test this connectivity.

. The script runs a variety of tests on the system and it displays results as it progresses. When it finishes it writes a log of the session to a file named `prerequisites-test-<timestamp>.log` in the directory `/opt/netapp/install_logs`.

.Result

If all the prerequisites tests ran successfully, you can install BlueXP classification on the host when you are ready.

If any issues were discovered, they are categorized as "Recommended" or "Required" to be fixed. Recommended issues are typically items that would make the BlueXP classification scanning and categorizing tasks run slower. These items do not need to be corrected - but you may want to address them.

If you have any "Required" issues, you should fix the issues and run the Prerequisites test script again.
