---
sidebar: sidebar
permalink: task-saved-searches.html
keywords: default searches, policies, private data, edit query
summary: Saved searches (previously known as policies) enable you to easily access custom queries for your classification scans. 
---
= Create saved searches in BlueXP classification
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP classification supports saving your search queries. With a saved search, you can create custom filters provide search results in the Investigation page for commonly requested compliance queries. BlueXP classification also includes predefined saved searches based on common requests. 

[NOTE]
In versions of BlueXP classification earlier than 1.43, saved searches were called xref:task-using-policies.adoc[policies].


== Create a saved search 


== Edit a saved search 


== Delete a saved search


== Default searches

BlueXP classification provides the following system-defined policies:

* **Data Subject names - High risk**
+
Files with more than 50 data subject names

* **Email Addresses - High risk**
+
Files with more than 50 email addresses or database columns with more than 50% of their rows containing email addresses 

* **Personal data - High risk**
+
Files with more than 20 personal data identifiers or database columns with more than 50% of their rows containing personal data identifiers

* **Private data - Stale over 7 years**
+
Files containing personal or sensitive personal information, last modified more than 7 years ago

* **Protect - High** 
+
Files or database columns that contain a password, credit card information, IBAN number, or social security number

* **Protect - Low**
+
Files that have not been accessed for more than 3 years

* **Protect - Medium**
+
Files that contain files or database columns with personal data identifiers including ID numbers, tax identification numbers, drivers license numbers, medicinal IDs, or passport numbers

* **Sensitive Personal data - High risk**
+
Files with more than 20 sensitive personal data identifiers or database columns with greater than 50% of their rows containing sensitive personal data