---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense
summary: Learn what's new in Cloud Data Sense.
---

= What's new with Cloud Data Sense
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Cloud Data Sense.

// tag::whats-new[]
== 2 April 2023 (version 1.22)

=== first new feature

df

=== 2nd feature

dfdf

== 7 March 2023 (version 1.21)

=== New functionality to add your own custom categories from the Data Sense UI

Data Sense now enables you to add your own custom categories so that Data Sense will identify the files that fit into those categories. Data Sense has many https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories[predefined categories], so this feature enables you to add custom categories to identify where information that is unique to your organization are found in your data.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories[Learn more^].

=== Now you can add custom keywords from the Data Sense UI

Data Sense has had the ability to add custom keywords that Data Sense will identify in future scans for a while. However, you needed to log into the Data Sense Linux host and use a command line interface to add the keywords. In this release, the ability to add custom keywords is in the Data Sense UI, making it very easy to add and edit these keywords.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words[Learn more about adding custom keywords from the Data Sense UI^].

=== Ability to have Data Sense *not* scan files when the "last access time" will be changed

By default, if Data Sense doesn't have adequate "write" permissions, the system won't scan files in your volumes because Data Sense can't revert the "last access time" to the original timestamp. However, if you don't care if the last access time is reset to the original time in your files, you can override this behavior in the Configuration page so that Data Sense will scan the volumes regardless of permissions.

In conjunction with this capability, and new filter named "Scan Analysis Event" has been added so you can view the files that were not classified because Data Sense couldn't revert last accessed time, or the files that were classified even though Data Sense couldn't revert last accessed time.

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp[Learn more about the "Last access time timestamp" and the permissions Data Sense requires].

=== Three new types of personal data are identified by Data Sense

Data Sense can identify and categorize files that contain the following types of data:

* Botswana Identity Card (Omang) Number
* Botswana Passport Number
* Singapore National Registration Identity Card (NRIC)

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data[See all the types of personal data that Data Sense can identify in your data].

=== Updated functionality for directories

* The "Light CSV Report" option for Data Investigation Reports now includes information from directories.
* The "Last Accessed" time filter now shows the last accessed time for both files and directories.

=== Installation enhancements

* Data Sense can be installed on Linux hosts that are running CentOS Stream 8.
* The Data Sense installer for sites without internet access (dark sites) now performs a pre-check to make sure your system and networking requirements are in place for a successful installation.
* Installation audit log files are saved now; they are written to `/ops/netapp/install_logs`.

== 5 February 2023 (version 1.20)

=== Ability to send Policy-based notification emails to any email address

In earlier versions of Cloud Data Sense you could send email alerts to the BlueXP users in your account when certain critical Policies return results. This feature enables you to get notifications to protect your data when you're not online. Now you can also send email alerts from Policies to any other users - up to 20 email addresses - who are not in your BlueXP account. 

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found[Learn more about sending email alerts based on Policy results].

=== Now you can add personal patterns from the Data Sense UI

Data Sense has had the ability to add custom "personal data" that Data Sense will identify in future scans for a while. However, you needed to log into the Data Sense Linux host and use a command line to add the custom patterns. In this release, the ability to add personal patterns using a regex is in the Data Sense UI, making it very easy to add and edit these custom patterns.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex[Learn more about adding custom patterns from the Data Sense UI^].

=== Ability to move 15 million files using Data Sense

In the past you could have Data Sense move a maximum of 100,000 source files to any NFS share. Now you can move up to 15 million files at a time. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share[Learn more about moving source files using Data Sense].

=== Ability to see the number of users who have access to SharePoint Online files

The filter "Number of users with access" now supports files stored in SharePoint Online repositories. In the past only files on CIFS shares were supported. Note that SharePoint groups that are not active directory based will not be counted in this filter at this time.

=== New "Partial Success" status has been added to the Action Status panel

The new "Partial Success" status indicates that a Data Sense action is finished and some items failed and some items succeeded, for example, when you are moving or deleting 100 files. Additionally, the "Finished" status has been renamed to "Success". In the past, the "Finished" status might list actions that succeeded and that failed. Now the "Success" status means that all actions succeeded on all items. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html[See how to view the Actions Status panel].
// end::whats-new[]

== 9 January 2023 (version 1.19)

=== Ability to view a chart of files that contain sensitive data and that are overly permissive

The Governance dashboard has added a new _Sensitive Data and Wide Permissions_ area that provides a heatmap of files that contain sensitive data (including both sensitive and sensitive personal data) and that are overly permissive. This can help you to see where you may have some risks with sensitive data. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions[Learn more].

=== Three new filters are available in the Data Investigation page

New filters are available to refine the results that display in the Data Investigation page:

* The "Number of users with access" filter shows which files and folders are open to a certain number of users. You can choose a number range to refine the results - for example, to see which files are accessible by 51-100 users.
* The "Created Time", "Discovered Time", "Last Modified", and "Last Accessed" filters now allow you to create a custom date range instead of just selecting a pre-defined range of days. For example, you can look for files with a "Created Time" "older than 6 months", or with a "Last Modified" date within the "last 10 days".
* The "File Path" filter now enables you to specify paths that you want to exclude from the filtered query results. If you enter paths to both include and exclude certain data, Data Sense finds all files in the included paths first, then it removes files from excluded paths, and then it displays the results.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page[See the list of all the filters you can use to investigate your data].

=== Data Sense can identify the Japanese Individual Number

Data Sense can identify and categorize files that contain the Japanese Individual Number (also known as My Number). This includes both the Personal and Corporate My Number. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data[See all the types of personal data that Data Sense can identify in your data].

== 11 December 2022 (version 1.18)

=== On-premises installation enhancements

The following enhancements have been added for the on-prem Data Sense installation:

* Some additional prerequisites are now checked before the installation will start on an on-premises host. This helps to make sure your host system is 100% ready to have Data Sense software installed:
** test for sufficient space on `/var/lib/docker`, `/tmp`, and `/opt`
** test for the relevant permissions on all required folders
* In the Configuration page, the Working Environments section now displays the _Working Environment ID_ and the _Scanner Group_ name. You'll need to know the Working Environment ID if you plan to use multiple Data Sense hosts to provide additional processing power to scan your data sources.
* Also in the Configuration page, a new section shows the Scanner Groups you have set up, and the scanner nodes that are in each group.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html[Learn more about installing Data Sense on a single host server and on multiple hosts]. 

== 13 November 2022 (version 1.17)

=== Support for scanning SharePoint On-Premises accounts

Data Sense now can scan both SharePoint Online accounts and SharePoint On-Premises accounts (SharePoint Server). If you need to install SharePoint on your own servers, or in sites without internet access, now you can have Data Sense scan the user files in those accounts. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account[Learn more^].

=== Ability to rescan multiple directories (folders or shares) 

Now you can rescan multiple directories (folders or shares) immediately so that changes are reflected in the system. This allows you to prioritize rescanning of certain data before other data. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository[See how to rescan a directory^].

=== Ability to add additional on-premises "scanner" nodes to scan specific data sources

If you have installed Data Sense in an on-premises location, and you find that you need more scanning processing power to scan certain data sources, you can add more "scanner" nodes and assign them to scan those data sources. You can add the scanner nodes immediately after installing the manager node, or you can add a scanner node later.

If necessary, the scanner nodes can be installed on host systems that are physically closer to the data sources that you are scanning. The closer the scanner node is to the data, the better, because it reduces network latency as much as possible while scanning data. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment[See how to install scanner nodes to scan additional data sources^].

=== On-premises installers now perform a pre-check before starting the installation

When installing Data Sense on a Linux system, the installer checks whether the system meets all the necessary requirements (CPU, RAM, capacity, networking, etc.) before starting the actual installation. This helps catch issues *before* you spend time on the installation.

== 6 September 2022 (version 1.16)

=== Ability to rescan a repository immediately to reflect changes in files

If you need to rescan a particular repository immediately so that changes are reflected in the system, you can select the repository and rescan it. This allows you to prioritize rescanning of certain data before other data. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository[See how to rescan a directory^].

=== New filter for the status of Data Sense scanning in the Data Investigation page

The “Analysis Status” filter enables you to list the files that are in a specific stage of Data Sense scanning. You can select an option to show the list of files that are *Pending First Scan*, *Completed* being scanned, *Pending Rescan*, or that have *Failed* to be scanned.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page[See the list of all the filters you can use to investigate your data^].

=== Data Subjects are now considered part of "personal data" found in scans

Data Sense now recognizes Data Subjects as part of the Personal Results that appear in the Compliance Dashboard. Additionally, when performing a search in the Investigation page, you can select "Data Subjects" under "Personal Data" to view only files that contain data subjects.

=== Data Sense breadcrumb files are now considered part of "Categories" found in scans

Data Sense now recognizes breadcrumb files as part of the Categories that appear in the Compliance Dashboard. These are files Data Sense creates when moving files from the source location to an NFS share. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share[Learn more about how breadcrumb files are created^].

Additionally, when performing a search in the Investigation page, you can select "Data Sense Breadcrumbs" under "Category" to view only Data Sense breadcrumb files.

== 7 August 2022 (version 1.15)

=== Five new types of personal data from New Zealand are identified by Data Sense

Data Sense can identify and categorize files that contain the following types of data:

* New Zealand Bank Account Number
* New Zealand Driver's License Number
* New Zealand IRD Number (Tax ID)
* New Zealand NHI (National Health Index) Number
* New Zealand Passport Number

link:reference-private-data-categories.html#types-of-personal-data[See all the types of personal data that Data Sense can identify in your data].

=== Ability to add a breadcrumb file to indicate why a file was moved

When you use the Data Sense feature to move source files to an NFS share, now you can leave a breadcrumb file in the location of the moved file. A breadcrumb file helps your users understand why a file was moved from its original location. For each moved file, the system creates a breadcrumb file in the source location named `<filename>-breadcrumb-<date>.txt` to show the location where the file was moved and the user who moved the file. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share[Learn more^].

=== Personal data and Sensitive Personal data found in your Directories are shown in Investigation results

The Data Investigation page now shows results for Personal data and Sensitive Personal data found within your directories (folders and shares). https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data[See an example here^].

=== View the status of how many volumes, buckets, etc. have been successfully classified

When viewing the individual repositories that Data Sense is scanning (volumes, buckets, etc.), now you can see how many have been "Mapped", and how many have been "Classified". Classification takes longer as the full AI identification is being performed on all data. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories[See how to view this information^].

=== Now you can add custom patterns that Data Sense will identify in your data

There are two ways that you can add custom "personal data" that Data Sense will identify in future scans. This allows you to see the full picture about where potentially sensitive data resides in all your organizations' files.

* You can add custom keywords from a text file.
* You can add a personal pattern using a regular expression (regex).

These keywords and patterns are added to the existing predefined patterns that Data Sense already uses, and the results will be visible under the Personal patterns section. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html[Learn more^].

== 6 July 2022 (version 1.14)

=== Now you can view the users and groups who have access to your directories

In the past you could view the types of open permissions granted on individual files. Now you can view a list of all users or groups who have access to directories (folders and file shares), and the types of permissions they have. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories[See how to view the users and groups that have access to your folders and file shares].

=== You can "pause" scanning a repository to temporarily stop scanning certain content

Pausing scanning means that Data Sense won't perform future scanning on any additions or changes to a volume or bucket, but that all the current results will still be available in the system. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository[See how to pause and resume scanning].

=== US driver's license data from three additional states can be identified by Data Sense

Data Sense can identify and categorize files that contain driver's license data from Indiana, New York, and Texas. link:reference-private-data-categories.html#types-of-personal-data[See all the types of personal data that Data Sense can identify in your data].

=== Policies now return directories that match the search criteria

In the past when you created a custom Policy, the results showed the files that matched the search criteria. Now the results also show the directories (folders and file shares) that match the query. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies[Learn more about creating policies].

=== Data Sense can move up to 100,000 files at a time now

If you plan to use Data Sense to move files from a scanned data source to an NFS share, the maximum number of files has been increased to 100,000 files. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share[See how to move files using Data Sense].

== 12 June 2022 (version 1.13.1)

=== Now you can download the results from the Data Investigation page as a .JSON report

After you have filtered the data in the Data Investigation page, now you can save the data as a report in a .JSON file that you can export to an NFS Share, in addition to saving the data to a .CSV file on your local system. Make sure Data Sense has the correct permissions for export access. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report[See how to create reports from the Data Investigation page].

=== Ability to uninstall Data Sense from the Data Sense UI

You can uninstall Data Sense to permanently remove the software from the host, and in the case of a cloud deployment, delete the virtual machine / instance on which Data Sense was deployed. Deleting the instance permanently deletes all the indexed information Data Sense has scanned. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html[See how].

=== Audit logging is now available to track the history of actions that Data Sense has performed

The audit log tracks the management activities that Data Sense has performed on files from all the working environments and data sources that Data Sense is scanning. The activities could be user generated (delete a file, create a policy, etc.) or policy generated (automatically add labels to files, automatically delete files, etc.).

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html[See more details about the audit log].

=== New Filter for number of sensitive identifiers in the Data Investigation page

The “Number of identifiers” filter enables you to list the files that have a certain number of sensitive identifiers - including both personal data and sensitive personal data. You can select a range like 1-10 or 501-1000 to view only the files that contain that number of sensitive identifiers.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page[See the list of all the filters you can use to investigate your data].

=== Now you can edit existing policies that you created

If you need to make a change to a custom policy that you created in the past, now you can edit the policy instead of creating a new policy. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies[See how to edit a policy].

== 11 May 2022 (version 1.12.1)

=== Support added for scanning data in Google Drive accounts

Now you can add your Google Drive accounts to Data Sense in order to scan the documents and files from those Google Drive accounts. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html[See how to scan your Google Drive accounts].

Data Sense can identify Personal Identifiable Information (PII) within the following Google file types from the Google Docs suite -- Docs, Sheets, and Slides -- in addition to the https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files[existing file types].

=== Directory level view added to the Data Investigation page

In addition to viewing and filtering data from all your files and databases, now you can view and filter data based on all the data within folders and shares in the Data Investigation page. Directories will be indexed for scanned CIFS and NFS shares, and for OneDrive, SharePoint, and Google Drive folders. So now you can view permissions and manage your data on the directory level. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page[See how to select the Directories view of your scanned data].

=== Expand groups to show the users/members that have permissions to access a file

As part the Data Sense permissions capabilities, now you can view the list of users and groups that have access to a file. Each group can be expanded to show the list of users in the group. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files[See how to view users and groups who have read and/or write permissions to your files].

=== Two new Filters have been added to the Data Investigation page

* The “Directory type” filter enables you to refine your data to see folders or shares only. The results will be shown in the new *Directories* tab.
* The "User / Group Permissions" filter enables you to list the files, folders, and shares that a specific user or a group has read and/or write permissions to. You can select multiple users and/or group names - or enter a partial name.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page[See the list of all the filters you can use to investigate your data].

== 5 April 2022 (version 1.11.1)

=== Four new types of Australian personal data can be identified by Data Sense

Data Sense can identify and categorize files that contain the Australian TFN (Tax File Number), Australian Driver's License Number, Australian Medicare Number, and Australian Passport Number. link:reference-private-data-categories.html#types-of-personal-data[See all the types of personal data that Data Sense can identify in your data].

=== Global Active Directory server can be an LDAP server now

The global Active Directory server you integrate with Data Sense can be an LDAP Server now in addition to the previously supported DNS Server. link:task-add-active-directory-datasense.html[Go here for details].

== 15 March 2022 (version 1.10.0)

=== New Filter to show the files to which a specific user or a group has read or write permissions

A new Filter called "User / Group Permissions" has been added so you can list the files that a specific user or a group has read and/or write permissions to. You can select one or more user and/or group names - or enter a partial name. This functionality is available for volumes on Cloud Volumes ONTAP, on-prem ONTAP, Azure NetApp Files, Amazon FSx for ONTAP, and File Shares.

=== Data Sense can determine the permissions for files in SharePoint and OneDrive accounts

Data Sense can read the permissions that exist for files that are being scanned in OneDrive accounts and SharePoint accounts now. This information appears in the Investigation pane details for files and in the Open Permissions area in the Governance Dashboard.

=== Two additional types of personal data can be identified by Data Sense

* French INSEE - The INSEE code is a numerical code used by the French National Institute for Statistics and Economic Studies (INSEE) to identify various entities.
* Passwords - This information is identified using proximity validation by looking for permutations of the word "password" next to a alphanumeric string. The number of items found will be listed under "Personal Results" in the Compliance Dashboard. You can search for files that contain passwords in the Investigation pane using the Filter *Personal Data > Password*.

=== Support for scanning OneDrive and SharePoint data when deployed in a dark site

When you've deployed Cloud Data Sense on a host in an on-premises site that doesn't have internet access, now you can scan local data from OneDrive accounts or SharePoint accounts. link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements[You'll need to allow access to the following endpoints.]

=== The Beta capability to use Cloud Data Sense to scan your Cloud Backup files has been discontinued in this release

== 9 February 2022

=== Added support for scanning Microsoft SharePoint online accounts

Now you can add your SharePoint online accounts to Data Sense in order to scan the documents and files from your SharePoint sites. link:task-scanning-sharepoint.html[See how to scan your SharePoint accounts].

=== Data Sense can copy files from a data source to a target location and synchronize those files

This is helpful for situations where you’re migrating data and you want to catch any last changes that are being made to the files. This action uses the https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html[NetApp Cloud Sync^] functionality to copy and sync data from a source to a target.

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system[See how to copy and sync files].

=== New language support for DSAR reports

German and Spanish are now supported when searching for names of data subjects in order to create Data Subject Access Request (DSAR) reports. This report is designed to aid in your organization’s requirement to comply with GDPR or similar data privacy laws.

=== Three additional types of personal data can be identified by Data Sense

Data Sense can now find French social security numbers, French IDs, and French driver license numbers in files. link:reference-private-data-categories.html#types-of-personal-data[See the list of all personal data types that Data Sense identifies in scans].

=== Security group port changed for Data Sense communication to the Connector

The security group for the Cloud Manager Connector will use port 443 instead of port 80 for inbound and outbound traffic to and from the Data Sense instance for added security. Both ports remain open at this time, so you shouldn't see any issues, but you should update the security group in any older deployments of the Connector as port 80 will be deprecated in a future release.
