=== Version 1.43

This BlueXP classification release includes:

.Prioritize classification scans

BlueXP classification now supports the ability to prioritize Map & Classify scans in addition to Mapping-only scans, enabling you to select which scans are completed first. Prioritization of Map & Classify scans is supported during and before the scans begin. If you choose to prioritize a scan while it's in progress, both the mapping and classification scans are prioritized. 

For more information, see link:task-managing-repo-scanning.html#prioritize-scans[Prioritize scans].

.Support for Canadian personally identifiable information (PII) data categories

BlueXP classification scans now identify Canadian PII data categories for banking information, passport number, social insurance number, and driver's license number and health card number for all provinces and territories.

For more detail information, see xref:reference-private-data-categories.adoc#types-of-personal-data[Personal data categories].

.Custom classification (preview)

BlueXP classification now supports custom classifications for Map & Classify scans. With custom classifications, you can tailor BlueXP scans to capture data specific to your organization to ensure compliance with regular expressions. This feature is currently in preview. 

For more information, see xref:task-custom-classification.adoc[Add custom classifications].

.Saved Searches tab

The **Policies** tab has been renamed xref:task-using-policies.html[**Saved Searches**]. The functionality is the same. 

.Send scan events to audit log

BlueXP scan events can now be sent to the xref:task-audit-data-sense-actions.html[audit log]. BlueXP classification also supports sending classification events (when a scan is initiated and when it ends) to the link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline[BlueXP timeline^]. Sending classification scan events to the BlueXP timeline is only supported for working environments.

.Security updates 

* The Keras package has been updated, mitigating vulnerabilities (BDSA-2025-0107 and BDSA-2025-1984). 
* The Docker containers configuration has been updated. The container no longer has access to the host's network interfaces for crafting raw network packets. By reducing unnecessary access, the update mitigates potential security risks.

.Performance enhancements 

Code enhancements have been implemented to reduce RAM usage and improve the overall performance of BlueXP classification. 

.Bug fixes

Bugs that caused StorageGRID scans to fail, the investigation page filter options to not load, and the Data Discovery Assessment to not download for high volume assessments have been fixed. 