=== Version 1.43

This BlueXP classification release includes:



.Dashboard performance improvements
we improved loading time of the dashboard significantly.

.Prioritize classification scans

BlueXP classification now supports the ability to prioritize Map & Classify scans in addition to Mapping-only scans. Prioritization of Map & Classify scans is supported during and before the scans begin. If you choose to prioritize a scan while it's in progress, both the mapping and classification scans are prioritized. 

For more information, see link:task-managing-repo-scanning.html#prioritize-scans[Prioritize scans].

.Custom classification 
Custom classification - link to PRD. check if screenshots need to be updated.

.Policies tab name change
Change "Policies" tab name to "Saved Searches" - name changed, same functionality. check if screenshots need to be updated.

.Send scan events to audit log
Send scan events to audit log - send classification events to BXP timeline - start scan and end scan (in working environment level).

.Security updates 
Update keras package
The Docker containers configuration has been updated - this change ensures that the container no longer has access to the host's network interfaces for crafting raw network packets, thereby mitigating the associated security risks
Resource uitilization -
Upgrade scheduler - we saved approximately 20MB of RAM by using simpler python module "schedule" which does not schedule celery tasks.
Scanner node monitor task and worker conversion - we reduced RAM usage by convert both of them to simple scheduler.
Optimization of the celery worker - we saved approximately 3 GB of RAM in empty CDS installations.
Elastic duplication fix - Duplication in the elastic that cause the elastic to use more space than needed, after the fix the elastic uses less space than before.
Container merging - we merged similar containers into one to improve performance and reduce memory usage.

.Bug fixes
Bug fixed - investigation page filter options sometimes failed to load.
Bug fixed - storage grid scan fails

.Support for Canadian personally identifiable information (PII) data categories

BlueXP classification scans now identify Canadian PII data categories for banking information, passport number, social insurance number, and driver's license number and health card number for all provinces and territories. For more detail information, see xref:reference-private-data-categories.adoc#types-of-personal-data[Personal data categories].