=== Version 1.42

This BlueXP classification release includes:

.Bulk scanning for working environments

BlueXP classification now supports bulk operations for working environments. You can choose to enable Mapping scans, Map & Classify scans, disable scans, or create a custom configuration across volumes in working enviroment. If you make a selection for an individual volume, it overrides the bulk selection. To perform a bulk operation, navigate to the **Configuration** page and make your selection. 

.Download investigation report locally

BlueXP classification now supports the ability download data investigation reports to view in the browser. If you choose this option, the data investigation report is limited to the CSV format and the first 10,000 results. 

For more information, see link:task-investigate-data.html#create-the-data-investigation-report[Investigate the data stored in your organization with BlueXP classification].

.Prioritize classification scans

BlueXP classification now supports the ability to prioritize classification only scans in addition to Map & Classify scans. Prioritization of classification scans is supported during and before the scans begin. If you choose to prioritize a scan while it's progress, both the mapping and classification scans are prioritized. 

For more information, see link:task-managing-repo-scanning.html#prioritize-scans[Prioritize scans].
