=== Version 1.43

This BlueXP classification release includes:

.Prioritize classification scans

BlueXP classification now supports the ability to prioritize Map & Classify scans in addition to Mapping-only scans. Prioritization of Map & Classify scans is supported during and before the scans begin. If you choose to prioritize a scan while it's in progress, both the mapping and classification scans are prioritized. 

For more information, see link:task-managing-repo-scanning.html#prioritize-scans[Prioritize scans].

.Support for Canadian personally identifiable information (PII) data categories

BlueXP classification scans now identify Canadian PII data categories for banking information, passport number, social insurance number, and driver's license number and health card number for all provinces and territories.

For more detail information, see xref:reference-private-data-categories.adoc#types-of-personal-data[Personal data categories].

.Custom classification 

BlueXP classification now supports custom classifications for Map & Classify scans. With custom classifications, you can tailor BlueXP scans to capture data specific to your organization to ensure compliance with regular expressions. This feature is currently in preview. 

For more information, see xref:task-custom-classification.adoc[Add custom classifications].

.Saved Searches tab

The **Policies** tab has been renamed xref:task-using-policies.html[**Saved searches**]. The functionality is the same. 

.Send scan events to audit log

BlueXP scan events can now be sent to the xref:task-audit-data-sense-actions.html[audit log]. BlueXP classification also supports sending classification events (when a scan is initiated and when it ends) to the link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline[BlueXP timeline^]. Sending classification scan events to the BlueXP timeline is only supported for working environments.

.Security updates 

// keras pkg update impact? 
* The Keras pacakage has been updated, mitigating potential vulnerabilities. 
* The Docker containers configuration has been updated. The container no longer has access to the host's network interfaces for crafting raw network packets. By reducing unnecessary access, the update mitigates potential security risks.

.Performance enhancements 

//* The load time for the performance dashboard has been improved. 
* The Python module has been simplified and no longer schedules Celery tasks, saving approximately 20 MB of RAM. Additionally, the scanner node monitor task and worker conversion have been simplified, reducing RAM usage. 
* The Celery worker has been optimized to save approximately 3 GB of RAM. 
* Duplication has been eliminated in the elastic, reducing its size.  
* Similar containers have been merged to improve performance and reduce memory usage.

.Bug fixes

Bugs that caused StorageGRID scans to fail and the investigation page filter options to not load have been fixed. 