=== Version 1.46

This BlueXP classification release includes bug fixes and the following updates:

.Enhanced scan event insights in the BlueXP timeline

The BlueXP timeline now supports enhanced insights into scan events for BlueXP classification. The timeline now displays when the scan of a working environment begins, statuses of working environments, and any issues. Statuses for shares and working environments are only available for mapping scans. 

For more information about the BlueXP timeline, see link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html[Monitor BlueXP operations^].

.Support for RHEL 9.6
This release adds support for Red Hat Enterprise Linux v9.6 for manual on-premises installation of BlueXP classification, including dark site deployments.

The following operating systems require using the Podman container engine, and they require BlueXP classification version 1.30 or greater: Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4, and 9.5.